import { defineMessages } from '../../i18n/index.ts';

/**
 * Sample content for the UI kit gallery, in both languages, because half of what a
 * design review is checking is whether a component survives the longer of the two
 * strings.
 *
 * Deliberately not named `messages.ts`: that filename is globbed into the shipped i18n
 * catalog and into the production bundle, and the gallery must appear in neither.
 *
 * State names (`primary`, `inactive`, `elevated`) are prop values, not copy. They are
 * rendered as code, untranslated, so that what a reviewer reads is the same thing an
 * engineer types.
 */
export const galleryCopy = defineMessages({
  'zh-TW': {
    'gallery.title': 'UI 元件庫',
    'gallery.intro': '只在開發模式出現。每個元件、每種狀態，兩種語言都看得到。',
    'gallery.section.appBar': '1. 應用列',
    'gallery.section.button': '3. 按鈕',
    'gallery.section.card': '4. 卡片',
    'gallery.section.listRow': '5. 列表列',
    'gallery.section.statusChip': '6. 狀態標籤',
    'gallery.section.emptyState': '14. 空狀態',
    'gallery.section.bottomNav': '2. 底部導覽',
    'gallery.section.progress': '8. 進度',
    'gallery.section.banner': '13. 橫幅',
    'gallery.section.toast': '13. 提示訊息',
    'gallery.section.amountDisplay': '7. 金額顯示',
    'gallery.section.formFields': '11. 表單欄位',
    'gallery.appBar.screenTitle': '收據',
    'gallery.appBar.longTitle': '松本清藥妝店新宿東口駅前店的收據明細與退稅狀態',
    'gallery.appBar.back': '返回',
    'gallery.appBar.close': '關閉',
    'gallery.appBar.add': '新增收據',
    'gallery.button.save': '儲存',
    'gallery.button.import': '匯入備份',
    'gallery.button.guide': '看看這是怎麼運作的',
    'gallery.button.deleteAll': '刪除所有資料',
    'gallery.button.next': '下一步',
    'gallery.button.inactiveReason': '先選一位旅客，才能繼續。',
    'gallery.card.title': '這趟行程',
    'gallery.card.body': '11 張收據 · 10/28 離境',
    'gallery.card.linkTitle': '打包計畫',
    'gallery.card.linkBody': '哪些要隨身帶、哪些可以託運，出發前一晚看這張。',
    'gallery.row.shop': '松本清 新宿東口店',
    'gallery.row.shopLong': '松本清藥粧店新宿東口駅前店（東京都新宿區新宿三丁目）',
    'gallery.row.meta': '11/04 · ¥12,800 · 含稅',
    'gallery.row.traveler': '小美的收據',
    'gallery.row.listLabel': '收據',
    'gallery.chip.logged': '已記錄',
    'gallery.chip.registered': '已向業者登錄',
    'gallery.chip.customsConfirmed': '海關已確認',
    'gallery.chip.refundPending': '等待入帳',
    'gallery.chip.refunded': '已入帳',
    'gallery.chip.rejected': '未通過',
    'gallery.chip.refundDisputed': '金額有問題',
    'gallery.chip.notClaiming': '不辦這張',
    'gallery.chip.needsAction': '要處理',
    'gallery.chip.operatorUnknown': '業者未確認',
    'gallery.empty.headline': '還沒有收據',
    'gallery.empty.body': '在日本買東西、拿到收據之後，回來記一筆。',
    'gallery.empty.action': '記一筆收據',
    'gallery.empty.secondary': '退稅是怎麼運作的？',
    'gallery.nav.main': '主要導覽',
    'gallery.nav.home': '首頁',
    'gallery.nav.receipts': '收據',
    'gallery.nav.receiptsBadge': '，3 項待處理',
    'gallery.nav.airport': '機場模式',
    'gallery.nav.guide': '指南',
    'gallery.progress.label': '打包進度',
    'gallery.progress.value': '3 / 5',
    'gallery.progress.step': '步驟 2/5',
    'gallery.banner.attentionHeading': '還沒確認海關',
    'gallery.banner.attentionBody': '離境前，請先在機場模式完成海關確認，否則退稅可能無法入帳。',
    'gallery.banner.attentionAction': '前往機場模式',
    'gallery.banner.infoBody': '收據會自動依照店家與日期分組，方便一次登錄。',
    'gallery.banner.successBody': '備份已經匯出，檔案在你的下載資料夾。',
    'gallery.toast.saved': '收據已儲存',
    'gallery.toast.deleted': '收據已刪除',
    'gallery.toast.undo': '復原',
    'gallery.amount.tax': '消費稅',
    'gallery.amount.taxValue': '890 日圓',
    'gallery.amount.estimate': '預估淨退',
    'gallery.amount.estimateValue': '預估淨退，24,860 日圓',
    'gallery.amount.received': '實收',
    'gallery.amount.receivedValue': '實收，520 日圓',
    'gallery.amount.fee': '手續費',
    'gallery.amount.zero': '還沒有收據',
    'gallery.amount.zeroValue': '0 日圓',
    'gallery.field.shopLabel': '店家名稱',
    'gallery.field.shopHelper': '收據上印的店名就好，不用整理。',
    'gallery.field.shopError': '請輸入店家名稱',
    'gallery.field.amountLabel': '金額（未稅）',
    'gallery.field.amountAccessibleName': '金額（未稅），日圓',
    'gallery.field.amountDerived': '計算所得：含稅金額換算未稅',
    'gallery.field.amountError': '請輸入金額',
    'gallery.field.dateLabel': '購買日期',
    'gallery.field.dateToday': '今天',
    'gallery.field.dateDeadline': '海關期限 2027/02/02 · 90 天',
    'gallery.field.taxRateLegend': '稅率',
    'gallery.field.taxRate10Helper': '大部分商品',
    'gallery.field.taxRate8Helper': '食品、飲料（不含酒類）',
  },
  en: {
    'gallery.title': 'UI kit gallery',
    'gallery.intro':
      'Development build only. Every component, in each of its documented states, in both languages.',
    'gallery.section.appBar': '1. App bar',
    'gallery.section.button': '3. Buttons',
    'gallery.section.card': '4. Cards',
    'gallery.section.listRow': '5. List rows',
    'gallery.section.statusChip': '6. Status chips',
    'gallery.section.emptyState': '14. Empty state',
    'gallery.section.bottomNav': '2. Bottom navigation',
    'gallery.section.progress': '8. Progress',
    'gallery.section.banner': '13. Banner',
    'gallery.section.toast': '13. Toast',
    'gallery.section.amountDisplay': '7. Amount display',
    'gallery.section.formFields': '11. Form fields',
    'gallery.appBar.screenTitle': 'Receipts',
    'gallery.appBar.longTitle':
      'Receipt details and refund status for Matsumoto Kiyoshi Shinjuku East Exit Station Front',
    'gallery.appBar.back': 'Back',
    'gallery.appBar.close': 'Close',
    'gallery.appBar.add': 'Add receipt',
    'gallery.button.save': 'Save',
    'gallery.button.import': 'Import backup',
    'gallery.button.guide': 'See how this works',
    'gallery.button.deleteAll': 'Delete all data',
    'gallery.button.next': 'Next step',
    'gallery.button.inactiveReason': 'Choose a traveler first to continue.',
    'gallery.card.title': 'This trip',
    'gallery.card.body': '11 receipts · leaving 28 Oct',
    'gallery.card.linkTitle': 'Packing plan',
    'gallery.card.linkBody':
      'What to carry with you and what can go in the checked bag, the night before you fly.',
    'gallery.row.shop': 'Matsumoto Kiyoshi Shinjuku East',
    'gallery.row.shopLong':
      'Matsumoto Kiyoshi Drugstore Shinjuku East Exit Station Front Branch (Shinjuku 3-chome, Tokyo)',
    'gallery.row.meta': '4 Nov · ¥12,800 · tax included',
    'gallery.row.traveler': "Mei's receipts",
    'gallery.row.listLabel': 'Receipts',
    'gallery.chip.logged': 'Logged',
    'gallery.chip.registered': 'Registered',
    'gallery.chip.customsConfirmed': 'Customs confirmed',
    'gallery.chip.refundPending': 'Refund pending',
    'gallery.chip.refunded': 'Received',
    'gallery.chip.rejected': 'Rejected',
    'gallery.chip.refundDisputed': 'Amount disputed',
    'gallery.chip.notClaiming': 'Not claiming',
    'gallery.chip.needsAction': 'Needs you',
    'gallery.chip.operatorUnknown': 'Operator unknown',
    'gallery.empty.headline': 'No receipts yet',
    'gallery.empty.body': 'After you buy something in Japan, log the receipt here.',
    'gallery.empty.action': 'Log a receipt',
    'gallery.empty.secondary': 'How does the refund work?',
    'gallery.nav.main': 'Main navigation',
    'gallery.nav.home': 'Home',
    'gallery.nav.receipts': 'Receipts',
    'gallery.nav.receiptsBadge': ', 3 need action',
    'gallery.nav.airport': 'Airport Mode',
    'gallery.nav.guide': 'Guide',
    'gallery.progress.label': 'Packing progress',
    'gallery.progress.value': '3 / 5',
    'gallery.progress.step': 'Step 2 of 5',
    'gallery.banner.attentionHeading': 'Customs not confirmed yet',
    'gallery.banner.attentionBody':
      'Confirm customs in Airport Mode before you leave, or the refund may not arrive.',
    'gallery.banner.attentionAction': 'Go to Airport Mode',
    'gallery.banner.infoBody': 'Receipts group automatically by shop and day for one-tap logging.',
    'gallery.banner.successBody': 'Backup exported — the file is in your downloads.',
    'gallery.toast.saved': 'Receipt saved',
    'gallery.toast.deleted': 'Receipt deleted',
    'gallery.toast.undo': 'Undo',
    'gallery.amount.tax': 'Consumption tax',
    'gallery.amount.taxValue': '890 yen',
    'gallery.amount.estimate': 'Estimated net',
    'gallery.amount.estimateValue': 'Estimated net, 24,860 yen',
    'gallery.amount.received': 'Received',
    'gallery.amount.receivedValue': 'Received, 520 yen',
    'gallery.amount.fee': 'Fee',
    'gallery.amount.zero': 'No receipts yet',
    'gallery.amount.zeroValue': '0 yen',
    'gallery.field.shopLabel': 'Shop name',
    'gallery.field.shopHelper': 'The name printed on the receipt is fine as-is.',
    'gallery.field.shopError': 'Enter a shop name',
    'gallery.field.amountLabel': 'Amount (tax excluded)',
    'gallery.field.amountAccessibleName': 'Amount (tax excluded), yen',
    'gallery.field.amountDerived': 'Calculated from the tax-included amount',
    'gallery.field.amountError': 'Enter an amount',
    'gallery.field.dateLabel': 'Purchase date',
    'gallery.field.dateToday': 'Today',
    'gallery.field.dateDeadline': 'Customs deadline 2 Feb 2027 · 90 days',
    'gallery.field.taxRateLegend': 'Tax rate',
    'gallery.field.taxRate10Helper': 'Most goods',
    'gallery.field.taxRate8Helper': 'Food and drink, not alcohol',
  },
});

export type GalleryCopy = typeof galleryCopy;
